# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/kristofe/Documents/Projects/OpenCLFluids

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/kristofe/Documents/Projects/OpenCLFluids

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kristofe/Documents/Projects/OpenCLFluids/CMakeFiles /Users/kristofe/Documents/Projects/OpenCLFluids/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/kristofe/Documents/Projects/OpenCLFluids/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fluidsim

# Build rule for target.
fluidsim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fluidsim
.PHONY : fluidsim

# fast build rule for target.
fluidsim/fast:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/build
.PHONY : fluidsim/fast

GLLib/glhelper.o: GLLib/glhelper.cpp.o
.PHONY : GLLib/glhelper.o

# target to build an object file
GLLib/glhelper.cpp.o:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/GLLib/glhelper.cpp.o
.PHONY : GLLib/glhelper.cpp.o

GLLib/glhelper.i: GLLib/glhelper.cpp.i
.PHONY : GLLib/glhelper.i

# target to preprocess a source file
GLLib/glhelper.cpp.i:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/GLLib/glhelper.cpp.i
.PHONY : GLLib/glhelper.cpp.i

GLLib/glhelper.s: GLLib/glhelper.cpp.s
.PHONY : GLLib/glhelper.s

# target to generate assembly for a file
GLLib/glhelper.cpp.s:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/GLLib/glhelper.cpp.s
.PHONY : GLLib/glhelper.cpp.s

OpenCLManager.o: OpenCLManager.cpp.o
.PHONY : OpenCLManager.o

# target to build an object file
OpenCLManager.cpp.o:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/OpenCLManager.cpp.o
.PHONY : OpenCLManager.cpp.o

OpenCLManager.i: OpenCLManager.cpp.i
.PHONY : OpenCLManager.i

# target to preprocess a source file
OpenCLManager.cpp.i:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/OpenCLManager.cpp.i
.PHONY : OpenCLManager.cpp.i

OpenCLManager.s: OpenCLManager.cpp.s
.PHONY : OpenCLManager.s

# target to generate assembly for a file
OpenCLManager.cpp.s:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/OpenCLManager.cpp.s
.PHONY : OpenCLManager.cpp.s

OpenCLUtil.o: OpenCLUtil.cpp.o
.PHONY : OpenCLUtil.o

# target to build an object file
OpenCLUtil.cpp.o:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/OpenCLUtil.cpp.o
.PHONY : OpenCLUtil.cpp.o

OpenCLUtil.i: OpenCLUtil.cpp.i
.PHONY : OpenCLUtil.i

# target to preprocess a source file
OpenCLUtil.cpp.i:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/OpenCLUtil.cpp.i
.PHONY : OpenCLUtil.cpp.i

OpenCLUtil.s: OpenCLUtil.cpp.s
.PHONY : OpenCLUtil.s

# target to generate assembly for a file
OpenCLUtil.cpp.s:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/OpenCLUtil.cpp.s
.PHONY : OpenCLUtil.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/fluidsim.dir/build.make CMakeFiles/fluidsim.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... fluidsim"
	@echo "... rebuild_cache"
	@echo "... GLLib/glhelper.o"
	@echo "... GLLib/glhelper.i"
	@echo "... GLLib/glhelper.s"
	@echo "... OpenCLManager.o"
	@echo "... OpenCLManager.i"
	@echo "... OpenCLManager.s"
	@echo "... OpenCLUtil.o"
	@echo "... OpenCLUtil.i"
	@echo "... OpenCLUtil.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

